"""Small state-machine behavior contracts shared across supported targets."""

from sysmlc_models.validation import Entry, Input, Scenario

STATE_SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        "true-guard",
        "sm-examples/sm03-guard",
        "SM03::MachineRef",
        1000,
        (Entry(0, "idle"), Entry(0, "running")),
    ),
    Scenario(
        "false-guard",
        "sm-examples/sm03-guard",
        "SM03::MachineLiteralFalse",
        1000,
        (Entry(0, "idle"),),
    ),
    *(
        Scenario(
            f"assignment-{machine}",
            "sm-examples/sm04-assignment",
            f"SM04::{machine}",
            1000,
            (Entry(0, "idle"), Entry(0, "running")),
            attributes=values,
        )
        for machine, values in (
            ("MachineEntryIncrement", (("counter", 1),)),
            ("MachineExitDecrement", (("counter", 0),)),
            ("MachineMultiEntry", (("a", 1), ("b", 3))),
            ("MachineEntryAndExit", (("entered", 1), ("exited", 1))),
            ("MachineEntryShorthand", (("counter", 1),)),
            ("MachineExitShorthand", (("counter", 0),)),
        )
    ),
    Scenario(
        "effect-increment",
        "sm-examples/sm06-transition-effect",
        "SM06::MachineEffect",
        1000,
        (Entry(0, "idle"), Entry(0, "armed"), Entry(0, "running")),
        attributes=(("counter", 1),),
    ),
    Scenario(
        "effect-multiple-assignments",
        "sm-examples/sm06-transition-effect",
        "SM06::MachineEffectMulti",
        1000,
        (Entry(0, "idle"), Entry(0, "running")),
        attributes=(("a", 1), ("b", 3)),
    ),
    Scenario(
        "nested-composite",
        "sm-examples/sm08-nested-composite",
        "SM08::MachineNested",
        1000,
        (
            Entry(0, "idle"),
            Entry(0, "running::warming"),
            Entry(0, "running::hot"),
        ),
    ),
    Scenario(
        "nested-deep-exit",
        "sm-examples/sm08-nested-composite",
        "SM08::MachineCrossOut",
        1000,
        (
            Entry(0, "idle"),
            Entry(0, "running::warming"),
            Entry(0, "running::hot"),
            Entry(0, "stopped"),
        ),
    ),
    Scenario(
        "parallel-root",
        "sm-examples/sm09-parallel",
        "SM09::MachineParallel",
        1000,
        (
            Entry(0, "lights::off"),
            Entry(0, "sound::silent"),
            Entry(0, "lights::on"),
            Entry(0, "sound::beeping"),
        ),
        concurrent_entries=True,
    ),
    Scenario(
        "parallel-nested",
        "sm-examples/sm09-parallel",
        "SM09::MachineNestedParallel",
        1000,
        (
            Entry(0, "idle"),
            Entry(0, "dual::lights::off"),
            Entry(0, "dual::sound::silent"),
            Entry(0, "dual::lights::on"),
            Entry(0, "dual::sound::beeping"),
        ),
        attributes=(("count", 1),),
        concurrent_entries=True,
    ),
    Scenario(
        "nested-completion",
        "sm-examples/sm10-done",
        "SM10::MachineNestedDone",
        1000,
        (
            Entry(0, "running::warming"),
            Entry(0, "running::hot"),
            Entry(0, "running::done"),
            Entry(0, "stopped"),
        ),
    ),
    Scenario(
        "composite-join",
        "sm-examples/sm10-done",
        "SM10::MachineCompositeJoin",
        1000,
        (
            Entry(0, "working::w1"),
            Entry(100, "working::done"),
            Entry(100, "finished"),
        ),
        inputs=(Input(100, "EventA"),),
    ),
    Scenario(
        "parallel-join-two",
        "sm-examples/sm10-done",
        "SM10::MachineParallelJoin",
        1000,
        (
            Entry(0, "working::a::a1"),
            Entry(0, "working::b::b1"),
            Entry(100, "working::a::done"),
            Entry(200, "working::b::done"),
            Entry(200, "finished"),
        ),
        inputs=(Input(100, "EventA"), Input(200, "EventB")),
        concurrent_entries=True,
    ),
    Scenario(
        "parallel-join-three",
        "sm-examples/sm10-done",
        "SM10::MachineParallelJoinThree",
        1000,
        (
            Entry(0, "working::a::a1"),
            Entry(0, "working::b::b1"),
            Entry(0, "working::c::c1"),
            Entry(100, "working::a::done"),
            Entry(200, "working::b::done"),
            Entry(300, "working::c::done"),
            Entry(300, "finished"),
        ),
        inputs=(
            Input(100, "EventA"),
            Input(200, "EventB"),
            Input(300, "EventC"),
        ),
        concurrent_entries=True,
    ),
    Scenario(
        "parallel-restart-clears-completion",
        "sm-examples/sm10-done",
        "SM10::MachineParallelRestart",
        1000,
        (
            Entry(0, "working::a::a1"),
            Entry(0, "working::b::b1"),
            Entry(100, "working::a::done"),
            Entry(200, "paused"),
            Entry(300, "working::a::a1"),
            Entry(300, "working::b::b1"),
            Entry(400, "working::b::done"),
            Entry(500, "working::a::done"),
            Entry(500, "finished"),
        ),
        inputs=(
            Input(100, "EventA"),
            Input(200, "Pause"),
            Input(300, "Resume"),
            Input(400, "EventB"),
            Input(500, "EventA"),
        ),
        concurrent_entries=True,
    ),
    *(
        Scenario(
            f"guarded-join-{go}",
            "sm-examples/sm10-done",
            "SM10::MachineGuardedJoin",
            1000,
            (
                Entry(0, "working::w1"),
                Entry(100, "working::done"),
                Entry(100, target),
            ),
            inputs=(Input(100, "EventA"),),
            overrides=(("go", go),),
        )
        for go, target in ((False, "rejected"), (True, "approved"))
    ),
    Scenario(
        "deep-completion-chain",
        "sm-examples/sm10-done",
        "SM10::MachineDeepJoin",
        1000,
        (
            Entry(0, "l1::l2::l3::leaf"),
            Entry(100, "l1::l2::l3::done"),
            Entry(100, "l1::l2::done"),
            Entry(100, "l1::done"),
            Entry(100, "finished"),
        ),
        inputs=(Input(100, "EventA"),),
    ),
    Scenario(
        "partial-join-stays-blocked",
        "sm-examples/sm10-done",
        "SM10::MachinePartialJoin",
        1000,
        (
            Entry(0, "working::a::a1"),
            Entry(0, "working::b::b1"),
            Entry(100, "working::a::done"),
            Entry(200, "working::b::b2"),
        ),
        inputs=(Input(100, "EventA"), Input(200, "EventB")),
        forbidden_states=("finished",),
        concurrent_entries=True,
    ),
    Scenario(
        "absolute-deadline",
        "sm-examples/sm13-time-trigger",
        "SM13::MachineAt",
        12000,
        (Entry(0, "idle"), Entry(8000, "running"), Entry(8000, "done")),
        ticks_ms=(7999, 8000),
        backends=("rosetta", "statix"),
    ),
    Scenario(
        "absolute-deadline-already-passed",
        "sm-examples/sm13-time-trigger",
        "SM13::MachineAtReentry",
        12000,
        (Entry(0, "idle"), Entry(1000, "away"), Entry(7000, "idle")),
        inputs=(Input(1000, "Leave"), Input(7000, "Back")),
        ticks_ms=(5000,),
        backends=("rosetta", "statix"),
        forbidden_states=("running",),
    ),
)
