"""Showcase behavior and testbench contracts, independent of target tests."""

from sysmlc_models.validation import Entry, Input, Milestone, Scenario

_WORKCELL_REGIONS = (
    (
        "producing::machining::spindle",
        "producing::machining::coolant",
        "producing::machining::monitor",
    ),
)
_REACTOR_REGIONS = (("reacting::agitation", "reacting::ventWatch"),)
_CROSSING_REGIONS = (("closed::bellCycle", "closed::passage"),)

_WORKCELL_START = (
    Entry(0, "cold"),
    Entry(100, "homing::axisX"),
    Entry(400, "homing::axisY"),
    Entry(700, "homing::axisZ"),
    Entry(1000, "homing::done"),
    Entry(1000, "ready"),
)


def _piece(start_ms: int) -> tuple[Entry, ...]:
    """Return the independently timed states of one workcell piece."""
    return tuple(
        Entry(start_ms + offset, "producing::" + state)
        for offset, state in (
            (0, "loadPart"),
            (500, "machining::spindle::spinUp"),
            (500, "machining::coolant::priming"),
            (500, "machining::monitor::watching"),
            (600, "machining::coolant::flowing"),
            (700, "machining::spindle::cutting"),
            (1600, "machining::coolant::done"),
            (1700, "machining::spindle::done"),
            (1800, "machining::monitor::done"),
            (1800, "unloadPart"),
            (2100, "done"),
        )
    )


_RECIPE_VALUES = (
    ("batchTarget", 1),
    ("inflowRate", 60.0),
    ("heatRate", 65.0),
    ("coolRate", 60.0),
    ("drainRate", 60.0),
)
_STATION_HANDSHAKE = (
    "idle",
    "handshake::checkCable",
    "handshake::lockConnector",
    "handshake::done",
    "authorizing",
)
_STATION_CHARGE_PREFIX = (
    *_STATION_HANDSHAKE,
    "authRetry",
    "authorizing",
    "rampUp",
    "rampUp",
    "rampUp",
    "bulk",
    "bulk",
    "bulk",
)

SHOWCASE_SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        "traffic-light-pedestrian",
        "showcase/traffic-light",
        "TrafficLight::TrafficLightBehavior",
        6000,
        (
            Entry(0, "showRed"),
            Entry(4000, "showGreen"),
            Entry(5000, "walkRequest"),
            Entry(5000, "showYellow"),
        ),
        ticks_ms=(3999, 4000),
        inputs=(Input(5000, "PedestrianRequest"),),
        backends=("rosetta",),
    ),
    Scenario(
        "stopwatch-start-stop",
        "showcase/stopwatch",
        "Stopwatch::StopwatchBehavior",
        4000,
        (
            Entry(0, "stopped"),
            Entry(100, "running"),
            Entry(1100, "running"),
            Entry(2100, "running"),
            Entry(3100, "running"),
            Entry(3500, "stopped"),
        ),
        ticks_ms=(1100, 2100, 3100),
        inputs=(Input(100, "StartCmd"), Input(3500, "StopCmd")),
        attributes=(("elapsed", 3),),
    ),
    Scenario(
        "thermostat-feedback",
        "showcase/thermostat",
        "Thermostat::ThermostatBehavior",
        20000,
        (),
        backends=("rosetta",),
        milestones=(
            Milestone("heating", 0, 0),
            Milestone("idle", 5000, 5000),
            Milestone("heating", 6000, 20000),
        ),
    ),
    Scenario(
        "thermostat-configured-setpoint",
        "showcase/thermostat",
        "Thermostat::ThermostatBehavior",
        11500,
        (),
        states=(*("heating" for _ in range(9)), "idle", "idle", "idle", "idle"),
        overrides=(("setpoint", 23.0), ("hysteresis", 1.0)),
        backends=("rosetta",),
    ),
    Scenario(
        "thermostat-invalid-setpoint",
        "showcase/thermostat",
        "Thermostat::ThermostatBehavior",
        1000,
        (),
        overrides=(("setpoint", -10.0),),
        backends=("rosetta",),
        failure="setpointPositive",
    ),
    Scenario(
        "thermostat-driverless-system",
        "showcase/thermostat",
        "Thermostat::thermostatSystem",
        2000,
        (),
        kind="part",
        backends=("rosetta",),
        milestones=(Milestone("plant::heating", 0, 0),),
    ),
    Scenario(
        "vending-pay-and-select",
        "showcase/vending-machine",
        "VendingMachine::VendingMachineBehavior",
        1000,
        (
            Entry(0, "idle"),
            Entry(100, "idle"),
            Entry(200, "paid"),
            Entry(300, "idle"),
        ),
        inputs=(
            Input(100, "Coin", (("value", 2),)),
            Input(200, "Coin", (("value", 2),)),
            Input(300, "Selection", (("product", "cola"),)),
        ),
        backends=("rosetta", "quake"),
    ),
    Scenario(
        "workcell-two-piece-batch",
        "showcase/milling-workcell",
        "MillingWorkcell::MillingWorkcellBehavior",
        10000,
        (
            *_WORKCELL_START,
            *_piece(1200),
            *_piece(3300),
            Entry(5400, "announcing"),
            Entry(5400, "ready"),
            Entry(7000, "done"),
        ),
        inputs=(
            Input(100, "PowerOn"),
            Input(1200, "StartBatch"),
            Input(7000, "Shutdown"),
        ),
        overrides=(("batchSize", 2),),
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_WORKCELL_REGIONS,
    ),
    Scenario(
        "workcell-vibration-retry",
        "showcase/milling-workcell",
        "MillingWorkcell::MillingWorkcellBehavior",
        10000,
        (
            *_WORKCELL_START,
            *(entry for entry in _piece(1200) if entry.time_ms <= 1900),
            Entry(2200, "producing::machining::monitor::tripped"),
            Entry(2200, "faultRecovery"),
            Entry(4200, "triage"),
            *_piece(4200),
            Entry(6300, "announcing"),
            Entry(6300, "ready"),
            Entry(8000, "done"),
        ),
        inputs=(
            Input(100, "PowerOn"),
            Input(1200, "StartBatch"),
            Input(2200, "VibrationSpike", (("level", 5),)),
            Input(8000, "Shutdown"),
        ),
        overrides=(("batchSize", 1),),
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_WORKCELL_REGIONS,
    ),
    Scenario(
        "batch-reactor-recipe",
        "showcase/batch-reactor",
        "BatchReactor::BatchReactorBehavior",
        20000,
        (
            Entry(0, "idle"),
            Entry(200, "filling"),
            Entry(1200, "filling"),
            Entry(1200, "heating"),
            Entry(2200, "heating"),
            Entry(2200, "reacting::agitation::stirring"),
            Entry(2200, "reacting::ventWatch::watching"),
            Entry(3700, "reacting::agitation::settling"),
            Entry(4700, "reacting::agitation::done"),
            Entry(5200, "reacting::ventWatch::done"),
            Entry(5200, "cooling"),
            Entry(6200, "cooling"),
            Entry(6200, "draining"),
            Entry(7200, "draining"),
            Entry(7200, "done"),
        ),
        inputs=(Input(200, "StartRecipe"),),
        overrides=_RECIPE_VALUES,
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_REACTOR_REGIONS,
    ),
    Scenario(
        "batch-reactor-overpressure",
        "showcase/batch-reactor",
        "BatchReactor::BatchReactorBehavior",
        20000,
        (
            Entry(0, "idle"),
            Entry(200, "filling"),
            Entry(1200, "filling"),
            Entry(1200, "heating"),
            Entry(2200, "heating"),
            Entry(2200, "reacting::agitation::stirring"),
            Entry(2200, "reacting::ventWatch::watching"),
            Entry(3000, "reacting::ventWatch::overpressure"),
            Entry(3000, "venting"),
            Entry(4500, "cooling"),
            Entry(5500, "cooling"),
            Entry(5500, "draining"),
            Entry(6500, "draining"),
            Entry(6500, "done"),
        ),
        inputs=(
            Input(200, "StartRecipe"),
            Input(3000, "PressureReading", (("bar", 9.5),)),
        ),
        overrides=_RECIPE_VALUES,
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_REACTOR_REGIONS,
    ),
    # Two ramp-up ticks and two bulk ticks give energy=22, temperature=46.
    # Both bulk exit guards hold (energy >= 19.8, temperature >= 45).
    # Either complete branch is permitted; the model gives neither priority.
    Scenario(
        "charging-session-thermal-detour",
        "showcase/charging-station",
        "ChargingStation::ChargingStationBehavior",
        12000,
        (),
        states=(
            *_STATION_CHARGE_PREFIX,
            "cooling",
            "cooling",
            "bulk",
            "topOff",
            "finishing",
            "idle",
        ),
        alternative_states=(
            (*_STATION_CHARGE_PREFIX, "topOff", "finishing", "idle"),
        ),
        inputs=(
            Input(200, "PlugIn"),
            Input(1200, "AuthResult", (("code", 7),)),
            Input(1600, "AuthResult", (("code", 1),)),
        ),
        overrides=(("tempLimit", 45.0), ("coolThreshold", 40.0)),
        backends=("rosetta",),
        attributes=(("sessions", 1),),
    ),
    Scenario(
        "charging-auth-exhaustion",
        "showcase/charging-station",
        "ChargingStation::ChargingStationBehavior",
        6000,
        (),
        states=(
            *_STATION_HANDSHAKE,
            "authRetry",
            "authorizing",
            "authRetry",
            "authorizing",
            "authRetry",
            "faulted",
            "idle",
        ),
        inputs=(
            Input(200, "PlugIn"),
            Input(1200, "AuthResult", (("code", 7),)),
            Input(4000, "AuthResult", (("code", 9),)),
            Input(5000, "Reset"),
        ),
        backends=("rosetta",),
    ),
    Scenario(
        "level-crossing-passage",
        "showcase/level-crossing",
        "LevelCrossing::LevelCrossingBehavior",
        7000,
        (
            Entry(0, "open"),
            Entry(300, "securing::warnLights"),
            Entry(700, "securing::bell"),
            Entry(1100, "securing::barrierDown"),
            Entry(1800, "securing::done"),
            Entry(1800, "closed::bellCycle::ringing"),
            Entry(1800, "closed::passage::waiting"),
            Entry(2800, "closed::bellCycle::quiet"),
            Entry(3300, "closed::bellCycle::done"),
            Entry(4000, "closed::passage::done"),
            Entry(4000, "opening::barrierUp"),
            Entry(4700, "opening::lightsOff"),
            Entry(5100, "opening::done"),
            Entry(5100, "open"),
        ),
        inputs=(Input(300, "TrainApproaching"), Input(4000, "TrainPassed")),
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_CROSSING_REGIONS,
    ),
    Scenario(
        "level-crossing-fault-reset",
        "showcase/level-crossing",
        "LevelCrossing::LevelCrossingBehavior",
        8000,
        (
            Entry(0, "open"),
            Entry(300, "securing::warnLights"),
            Entry(700, "securing::bell"),
            Entry(1100, "securing::barrierDown"),
            Entry(1300, "failSafe"),
            Entry(2500, "open"),
            Entry(3000, "securing::warnLights"),
            Entry(3400, "securing::bell"),
            Entry(3800, "securing::barrierDown"),
            Entry(4500, "securing::done"),
            Entry(4500, "closed::bellCycle::ringing"),
            Entry(4500, "closed::passage::waiting"),
            Entry(5300, "failSafe"),
            Entry(6500, "open"),
        ),
        inputs=(
            Input(300, "TrainApproaching"),
            Input(1300, "BarrierFault", (("severity", 3),)),
            Input(2500, "Reset"),
            Input(3000, "TrainApproaching"),
            Input(5300, "BarrierFault", (("severity", 1),)),
            Input(6500, "Reset"),
        ),
        backends=("rosetta",),
        concurrent_entries=True,
        parallel_regions=_CROSSING_REGIONS,
    ),
    *(
        Scenario(
            f"{name}-testbench",
            f"showcase/{name}",
            element,
            horizon,
            (),
            kind="part",
            backends=("rosetta",),
            milestones=(Milestone("tb::done", 0, deadline),),
            forbidden_states=("tb::fail",),
        )
        for name, element, horizon, deadline in (
            ("traffic-light", "TrafficLight::trafficLightSystem", 21000, 20000),
            ("stopwatch", "Stopwatch::stopwatchSystem", 14000, 13500),
            (
                "vending-machine",
                "VendingMachine::vendingMachineSystem",
                6000,
                5300,
            ),
            ("microwave", "Microwave::microwaveSystem", 6000, 5100),
            (
                "milling-workcell",
                "MillingWorkcell::millingWorkcellSystem",
                22000,
                21200,
            ),
            ("batch-reactor", "BatchReactor::batchReactorSystem", 40000, 30200),
            (
                "charging-station",
                "ChargingStation::chargingStationSystem",
                32000,
                31600,
            ),
            (
                "level-crossing",
                "LevelCrossing::levelCrossingSystem",
                15000,
                14000,
            ),
        )
    ),
)
