"""Model-owned execution expectations shared by target validation suites."""

from sysmlc_models._scenarios_showcase import SHOWCASE_SCENARIOS
from sysmlc_models._scenarios_state import STATE_SCENARIOS
from sysmlc_models.validation import Entry, Input, Milestone, Scenario

SCENARIOS: tuple[Scenario, ...] = (
    Scenario(
        "eventless-chain",
        "sm-examples/sm01-helloworld",
        "SM01::Machine",
        1000,
        (Entry(0, "idle"), Entry(0, "running")),
    ),
    Scenario(
        "signal-trigger",
        "sm-examples/sm02-event-trigger",
        "SM02::MachinePortless",
        1000,
        (Entry(0, "idle"), Entry(100, "running")),
        inputs=(Input(100, "Tick"),),
    ),
    Scenario(
        "exit-effect-entry-order",
        "sm-examples/sm07-firing-order",
        "SM07::MachineFiringOrder",
        1000,
        (Entry(0, "a"), Entry(0, "b")),
        attributes=(("exitAt", 1), ("effectAt", 2), ("entryAt", 3)),
    ),
    Scenario(
        "root-completion",
        "sm-examples/sm10-done",
        "SM10::MachineRootDone",
        1000,
        (Entry(0, "idle"), Entry(0, "running"), Entry(0, "done")),
    ),
    Scenario(
        "self-send",
        "sm-examples/sm11-send-effect",
        "SM11::MachineSelfSend",
        1000,
        (Entry(0, "idle"), Entry(0, "armed"), Entry(0, "fired")),
    ),
    Scenario(
        "do-send",
        "sm-examples/sm12-do-action",
        "SM12::MachineDoSend",
        1000,
        (Entry(0, "working"), Entry(0, "finished")),
    ),
    Scenario(
        "after-deadline",
        "sm-examples/sm13-time-trigger",
        "SM13::MachineAfterSeconds",
        6000,
        (Entry(0, "idle"), Entry(5000, "running"), Entry(5000, "done")),
        ticks_ms=(4999, 5000),
    ),
    Scenario(
        "default-duration",
        "sm-examples/sm13-time-trigger",
        "SM13::MachineAfterAttribute",
        121000,
        (Entry(0, "idle"), Entry(120000, "running"), Entry(120000, "done")),
        ticks_ms=(119999, 120000),
    ),
    Scenario(
        "configured-duration",
        "sm-examples/sm13-time-trigger",
        "SM13::MachineAfterAttribute",
        61000,
        (Entry(0, "idle"), Entry(60000, "running"), Entry(60000, "done")),
        ticks_ms=(59999, 60000),
        overrides=(("pickDuration", 1),),
    ),
    Scenario(
        "microwave-parallel-join",
        "showcase/microwave",
        "Microwave::MicrowaveBehavior",
        800,
        (
            Entry(0, "idle"),
            Entry(100, "cooking::heating::heater::warming"),
            Entry(100, "cooking::heating::turntable::rotating"),
            Entry(500, "cooking::heating::heater::done"),
            Entry(700, "cooking::heating::turntable::done"),
            Entry(700, "cooking::done"),
            Entry(700, "idle"),
        ),
        ticks_ms=(499, 500, 699, 700),
        inputs=(Input(100, "StartCmd"),),
        backends=("rosetta", "statix"),
        concurrent_entries=True,
    ),
    Scenario(
        "furuta-closed-loop",
        "showcase/furuta-pendulum/deterministic",
        "FurutaPendulum::furutaSystem",
        16000,
        (),
        backends=("quake", "rosetta"),
        kind="part",
        milestones=(
            Milestone("ctrl::stabilizing", 0, 15000),
            Milestone("mon::done", 0, 15000),
        ),
        forbidden_states=("mon::fail",),
        support="showcase/furuta-pendulum/furuta_physics.py",
    ),
    Scenario(
        "microwave-door-interrupt",
        "showcase/microwave",
        "Microwave::MicrowaveBehavior",
        800,
        (
            Entry(0, "idle"),
            Entry(100, "cooking::heating::heater::warming"),
            Entry(100, "cooking::heating::turntable::rotating"),
            Entry(200, "idle"),
        ),
        ticks_ms=(500, 700),
        inputs=(Input(100, "StartCmd"), Input(200, "DoorOpen")),
        concurrent_entries=True,
    ),
    Scenario(
        "microwave-pause-resume",
        "showcase/microwave",
        "Microwave::MicrowaveBehavior",
        1400,
        (
            Entry(0, "idle"),
            Entry(100, "cooking::heating::heater::warming"),
            Entry(100, "cooking::heating::turntable::rotating"),
            Entry(300, "cooking::paused"),
            Entry(600, "cooking::heating::heater::warming"),
            Entry(600, "cooking::heating::turntable::rotating"),
            Entry(1000, "cooking::heating::heater::done"),
            Entry(1100, "idle"),
        ),
        ticks_ms=(500, 999, 1000, 1200),
        inputs=(
            Input(100, "StartCmd"),
            Input(300, "PauseCmd"),
            Input(600, "ResumeCmd"),
            Input(1100, "DoorOpen"),
        ),
        backends=("rosetta", "statix"),
        concurrent_entries=True,
    ),
    *SHOWCASE_SCENARIOS,
    *STATE_SCENARIOS,
)
